apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: awx
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: prod
        revision: master
      - env: nonprod
        revision: master
  template:
    metadata:
      name: 'awx-{{.env}}'
    spec:
      project: 'lht-automationplatform-{{.env}}'
      source:
        repoURL: https://github.com/niki-playground/test_awx_repo.git
        targetRevision: '{{.revision}}'
        path: manifest/{{.env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: lht-awx-{{.env}}
      syncPolicy:
        syncoptions:
          - CreateNamespace=true
